[windows_vms]
172.16.99.241
172.16.99.242
172.16.99.243
172.16.100.111

[windows_vms:vars]
ansible_user=Administrador
ansible_connection=ssh
ansible_shell_type=powershell
ansible_shell_executable=powershell.exe
ansible_ssh_private_key_file=/home/ansible/.ssh/id_rsa