---
- name: Verificación inicial de nodos Windows
  hosts: windows_vms
  gather_facts: true

  tasks:
    - name: Comprobar respuesta ping
      ansible.windows.win_ping:

    - name: Obtener información del sistema operativo
      ansible.windows.win_powershell:
        script: |
          Get-CimInstance -ClassName Win32_OperatingSystem | Select-Object Caption, Version, OSArchitecture
      register: os_info

    - name: Mostrar detalles del OS
      ansible.builtin.debug:
        var: os_info.output