apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-data
  namespace: ansible
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: truenas-nfs