apiVersion: v1
kind: Service
metadata:
  name: ansible-runner-ssh
  namespace: truemetal-storage
spec:
  type: NodePort
  selector:
    app: ansible-runner
  ports:
  - port: 22
    targetPort: 22
    nodePort: 31022  # Puerto fijo para acceso externo (30000-32767)
    protocol: TCP
  externalTrafficPolicy: Cluster